---
- name: Install some development related tools (AUR)
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - entr
    - hugo
    - pygmentize
    - the_silver_searcher
    - ack
