---
- name: Disable suspend on lid close
  ini_file:
    path: "{{ logind_config }}"
    section: Login
    option: HandleLidSwitch
    value: ignore

- name: Power button should shutdown the laptop
  ini_file:
    path: "{{ logind_config }}"
    section: Login
    option: HandlePowerKey
    value: ignore
