---

- name: Install fonts
  pacman: name="{{ item }}" state=present
  with_items: "{{ japanese.fonts }}"
  tags:
    - japanese

- name: Install packages
  pacman: name="{{ item }}" state=present
  with_items: "{{ japanese.packages }}"

- name: Locale config
  locale_gen: name="ja_JP.UTF-8" state=present
