---

- name: Install fonts
  pacman: name="{{ japanese.fonts }}" state=present
  tags:
    - japanese

- name: Install packages
  pacman: name="{{ japanese.packages }}" state=present
  tags:
    - japanese

- name: Locale config
  locale_gen: name="ja_JP.UTF-8" state=present
  tags:
    - japanese
