---
- name: Install plugin deps
  pacman: name="{{ item }}" state=present
  loop:
    - flake8
    - autopep8
    - python-black
    - python-isort
    - python-pylint
    - python-pynvim
    - python-rope

- name: Make sure nvim plugins are installed correctly
  shell: 'nvim +PlugUpgrade +PlugUpdate +qall --headless'
  become: True
  become_user: "{{ user.name }}"
