---
- name: Install plugin deps
  pacman: name="{{ item }}" state=present
  loop:
    - python-pylint
    - python-rope
    - python-pynvim

- name: Make sure nvim plugins are installed correctly
  shell: 'nvim +PlugUpgrade +PlugUpdate +qall --headless'
  become: True
  become_user: "{{ user.name }}"
