---
- name: Install brightness control tool for intel cards
  aur:
    name: acpilight
    state: present
  become: True
  become_user: "{{ user.name }}"
  when: "'GenuineIntel' in ansible_processor"
