---
- name: Install khal, khard and friends
  aur:
    name: "{{ item }}"
    state: present
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - khal
    - khard
    - vdirsyncer
    - perl-text-autoformat
    - perl-ical-parser
