---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Enable and start OpenSSH
  service: name=sshd.service enabled=yes state=started
  when: ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  service: name=sshd.service enabled=no state=stopped
  when: ssh.enable_sshd == False

- name: Generate an OpenSSL public key in OpenSSH v2 format
  openssl_publickey:
    path: /tmp/insecure.pub
    privatekey_path: "{{ ansible_env.HOME }}/.vagrant.d/insecure_private_key"
    format: OpenSSH
  delegate_to: 127.0.0.1
  when: vagrant_testing

- name: Copy key to machine
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '/tmp/insecure.pub') }}"
  when: vagrant_testing

- name: Install sshfs
  pacman: name=sshfs state=present

- name: Install autossh
  pacman: name=autossh state=present

- name: Copy fuse configuration file
  copy: src=fuse.conf dest=/etc/fuse.conf

- name: Install keychain
  pacman: name=keychain state=present

- name: Install x11-ask-pass
  pacman: name=x11-ssh-askpass state=present

- name: Export SSH_ASKPASS environment variable
  lineinfile: dest=/etc/profile
              state=present
              line="export SSH_ASKPASS=\"/usr/lib/ssh/x11-ssh-askpass\""

- name: Make directory for user SSH key
  file: path=/home/{{ user.name }}/.ssh state=directory owner={{ user.name }} group={{ user.group }}

- name: Install user SSH key
  copy: src={{ ssh.user_key }} dest=/home/{{ user.name }}/.ssh/id_rsa mode=600 owner={{ user.name }} group={{ user.group }}
  when: ssh.user_key is defined

- name: Install Mosh
  pacman: name=mosh state=present
