---
- include: tlp.yml
- include: light-git.yml

- name: Copy touchpad configuration file
  copy: src=30-touchpad.conf dest=/etc/X11/xorg.conf.d/30-touchpad.conf

- name: Copy touchpad configuration file
  copy: src=00-keyboard.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf

- name: Push low battery warning script
  copy: src=lowbatt.sh dest=/usr/local/bin/lowbatt mode=0755

- name: Create systemd user path
  file:
    state: directory
    path: "/home/{{ username }}/.config/systemd/user/"
  become: yes
  become_user: "{{ username }}"

- name: Push low battery warning service file
  template:
    src=lowbatt.service.j2
    dest="/home/{{ username }}/.config/systemd/user/lowbatt.service"
  become: yes
  become_user: "{{ username }}"
  notify:
    - reload systemd userconfig

- name: Push low battery timer file
  template:
    src: lowbatt.timer.j2
    dest: "/home/{{ username }}/.config/systemd/user/lowbatt.timer"
  become: yes
  become_user: "{{ username }}"
  notify:
    - reload systemd userconfig
    - restart lowbatt

- name: Enable and start lowbatt timer
  service:
    name: lowbatt.timer
    enabled: yes
    state: started
    user: yes
  become: yes
  become_user: "{{ username }}"
