---
- name: Install pass
  pacman: name=pass state=present

- name: Install pass-otp
  aur: name=pass-otp
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install pass-update
  aur: name=pass-update
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install rofi-pass
  aur: name=rofi-pass
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur
    - rofi
