---
- name: Make sure pass is installed
  pacman:
    name: pass
    state: present

- name: Clone password store git repo
  git:
    repo: "{{ pass.repo }}"
    dest: "/home/{{ user.name }}/.password-store"
    accept_hostkey: yes
    update: no
    key_file: "{{ pass.ssh_key_path|default(omit) }}"
  when: pass.repo is defined
  become: yes
  become_user: "{{ user.name }}"
