---
- name: Install pass
  pacman: name=pass state=present

- name: Install pass-otp
  aur: name=pass-otp
  tags:
    - aur

- name: Install pass-update
  aur: name=pass-update
  tags:
    - aur

- name: Install rofi-pass
  aur: name=rofi-pass
  tags:
    - aur
    - rofi
