---
- name: Install i3
  package:
    name: i3-wm
    state: present

- name: Verify that default applications file exists
  file:
    path: '/etc/xdg/mimeapps.list'
    state: touch
  tags:
    - debug

- name: Verify header in default applications file
  lineinfile:
    dest=/etc/xdg/mimeapps.list
    state=present
    line='[Default Applications]'
    insertbefore=BOF
  tags:
    - debug

- include_tasks: utils.yml
- include_tasks: rofi.yml
