---
- name: Install rofi
  package: name=rofi state=present
  tags:
    - rofi

- name: Install tools that extend/use rofi
  aur:
    name: "{{ item }}"
    state: present
  with_items:
    - rofi-pass
    - rofi-dmenu
