---
- name: Install rofi
  package: name=rofi state=present
  tags:
    - rofi

- name: Install tools that extend/use rofi
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - rofi-pass
    - rofi-dmenu
