- name: Install additional tools
  pacman:
    name: "{{ item }}"
  with_items:
    - i3lock
    - i3blocks
    - i3status
    - dunst
    - redshift
    - compton

- name: Install polybar
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - polybar-git
  tags:
    - aur
    - polybar
