---
- name: Install vagrant
  pacman:
    name: vagrant
    state: present

- name: Get list of current vagrant plugins
  command: 'vagrant plugin list'
  register: current_vagrant_plugins
  become: true
  become_method: 'su'
  become_user: "{{ user.name }}"

- name: Install vagrant plugins
  command: "/usr/bin/vagrant plugin install {{ item }}"
  ignore_errors: True
  with_items: "{{ vagrant_plugins }}"
  when: "current_vagrant_plugins.stdout.find(item) == -1"
  become: true
  become_method: 'su'
  become_user: "{{ user.name }}"

- name: Install consul
  pacman: name=consul state=present

- name: Install terraform
  pacman: name=terraform state=present

- name: Install vault and nomad
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - vault-bin
    - nomad
  tags:
    - aur
