
---
- name: Install gajim
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items: "{{ gajim_packages }}"
- name: Install gajim plugins
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items: "{{ gajim_plugins }}"
