---
- name: Installing python3
  package: name=python3 state=present

- name: Installing go
  package: name=go state=present

- name: Installing ruby
  package: name=ruby state=present

- name: Install rbenv
  aur:
    name: rbenv
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install prompt_toolkit
  pip:
    name: prompt_toolkit
    virtualenv: /usr/local/env/prompt_toolkit
    virtualenv_command: virtualenv3

- name: Install ptpython
  pip:
    name: ptpython
    virtualenv: /usr/local/env/prompt_toolkit
    virtualenv_command: virtualenv3

- name: Link ptpython to bin
  file:
    src: /usr/local/env/prompt_toolkit/bin/ptpython
    dest: /usr/local/bin/ptpython
    state: link

