---
- name: Create user-tmpfiles.d
  file:
    path: /home/{{ user.name }}/.config/user-tmpfiles.d
    state: directory
    mode: '0700'
  become: True
  become_user: "{{ user.name }}"

- name: Copy auto download-dir-clean config
  copy:
    src: download-dir-cleanup.conf
    dest: /home/{{ user.name }}/.config/user-tmpfiles.d/download-dir-cleanup.conf
    mode: '0700'
  become: True
  become_user: "{{ user.name }}"

- name: Enable cleaup-timer
  systemd:
    name: systemd-tmpfiles-clean.timer
    enabled: yes
    state: started
    scope: user
  become: True
  become_user: "{{ user.name }}"
