---
- name: Install reversing packages
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ghidra
    - binwalk
    - gdb
    - radare2

- name: Install ida-free
  aur:
    name: ida-free
    user: "{{ user.name }}"
  tags:
    - aur
