---
- name: Install borg
  pacman: name={{ item }} state=present
  with_items:
    - python-llfuse
    - borg

- name: Install borgmatic
  aur: 
    name: borgmatic
  become: True
  become_user: "{{ user.name }}"
  tags:
    - aur
