---
- name: Install borg
  pacman: name={{ item }} state=present
  with_items:
    - python-llfuse
    - borg

- name: Install borgmatic
  pip:
    name: borgmatic
    virtualenv: /usr/local/env/borgmatic
    virtualenv_command: virtualenv3

- name: Link borgmatic to bin
  file:
    src: /usr/local/env/borgmatic/bin/borgmatic
    dest: /usr/local/bin/borgmatic
    state: link
