---
- name: Install borg
  pacman: name={{ item }} state=present
  with_items:
    - python-llfuse
    - borg

- name: Install borgmatic
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - python-pykwalify
    - borgmatic
  tags:
    - aur
