---
- name: Install abook
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - abook

- name: Install Little Brother Database and friends
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - lbdb
