---
- name: Install abook
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - abook

- name: Install Little Brother Database and friends
  aur:
    name: "{{ item }}"
    state: present
  with_items:
    - lbdb
