---
- include: ffmpeg.yml
- include: mpv.yml
- include: abcde.yml
- include: xfburn.yml
- include: imagemagick.yml
- include: gimp.yml
- include: feh.yml
- include: imv.yml
- include: teiler.yml
- include: qcode.yml

- name: Install music players
  pacman: name={{ item }} state=present
  with_items:
    - libmad
    - cmus

- name: Install misc media codecs and helpers
  pacman: name={{ item }} state=present
  with_items:
    - flac
    - lame
    - gst-libav
    - gst-plugins-good
    - exiv2
    - perl-image-exiftool
    - opus-tools

- name: Install streamlink
  package:
    name: streamlink
    state: present

- name: Install youtube-dl
  package:
    name: youtube-dl
    state: present

- name: Install aria2 used by youtube-dl
  package:
    name: aria2
    state: present

- name: Install playerctl
  package:
    name: playerctl
    state: present
