---
- name: Install missing deps
  pacman: name=qt5-x11extras state=present

- name: Install teiler and dependencies
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - xininfo-git
    - copyq-git
    - teiler-git
  tags:
    - aur
    - teiler
