---
- name: Create user-tmpfiles.d
  file:
    path: /home/{{ user.name }}/.config/user-tmpfiles.d
    state: directory
    mode: '0700'
    owner: "{{ user.name }}"

- name: Copy auto download-dir-clean config
  template:
    src: clean_dl_dir.conf.j2
    dest: /home/{{ user.name }}/.config/user-tmpfiles.d/clean_dl_dir.conf
    mode: '0700'
    owner: "{{ user.name }}"

- name: Copy auto cache-dir-clean config
  template:
    src: clean_cache_dir.conf.j2
    dest: /home/{{ user.name }}/.config/user-tmpfiles.d/clean_cache_dir.conf
    mode: '0700'
    owner: "{{ user.name }}"

- name: Enable cleaup-timer
  systemd:
    name: systemd-tmpfiles-clean.timer
    enabled: yes
    state: started
    scope: user
  become: True
  become_user: "{{ user.name }}"
