---
- name: Install docker and related tools
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    append: yes
    groups: "{{ docker_group }}"

- name: Enable and start the docker server
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
