---
- name: Install docker and related tools
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages }}"

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    append: yes
    groups: "{{ docker_group }}"

- name: Enable and start the docker server
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes

- name: Get a list of current docker base images
  shell: "docker images --format={% raw %}'{{ .Repository }}:{{ .Tag }}'{% endraw %}"
  register: current_docker_images

- name: Pull some base docker images
  shell: "docker pull {{item}}"
  with_items: "{{ docker_base_images }}"
  when:
    - docker_base_images is defined
    - "current_docker_images.stdout.find(item) == -1"

