---
- name: Install anki
  pacman: name=anki state=present

- name: Jail anki
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/anki
        state=link
  tags:
    - firejail

- name: Push anki firejail profile
  copy: src=firejail/anki.profile dest=/usr/local/etc/firejail/anki.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail

- name: Download addons from git
  git:
    repo: "{{ item.value }}"
    dest: "/home/{{ user.name }}/.local/share/Anki2/addons21/{{ item.key }}"
  become: True
  become_user: "{{ user.name }}"
  with_dict: "{{ anki.addons.git }}"

- name: Install anki addons
  include_role:
    name: anki
    tasks_from: addon
  vars:
    addonid: "{{ item }}"
  with_items: "{{ anki.addons.official }}"
