---
- name: Install GNUradio
  pacman: name=gnuradio user={{ user.name }}

- name: Install hamlib
  aur: name={{ item }} user={{ user.name }}
  become: True
  become_user: "{{ user.name }}"
  with_items:
    - perl-opcodes
    - hamlib
  tags:
    - aur

- include: rtl-sdr.yml
- include: radio_mgmt.yml
- include: radio_ops.yml
