---
- name: Installing Zsh and git
  package:
    name: [ 'zsh', 'git' ]
    state: present
  register: installation

- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  become: yes
  become_user: "{{ user.name }}"
