---
- name: Install some nice things
  pacman:
    name: "{{ item }}"
  loop:
    - cowsay
    - ccze
    - lolcat
    - diff-so-fancy
    - fd
    - bat
    - fzf
    - the_silver_searcher
    - ripgrep
    - termdown
    - lsd
    - tldr

- name: Install some nice things, coming from AUR
  aur:
    name: toilet
    user: "{{ user.name }}"
  tags:
    - aur
