---
- name: Install some nice things
  pacman:
    name: "{{ item }}"
  loop:
    - cowsay
    - ccze
    - lolcat
    - diff-so-fancy

- name: Install some nice things, coming from AUR
  aur:
    name: toilet
    user: "{{ user.name }}"
