---
- name: Copy udev rule
  copy: src=60-ssd.rules dest=/etc/udev/rules.d/60-ssd.rules

- name: Install hdparm
  pacman: name=hdparm state=present

- name: Check for TRIM support
  shell: "hdparm -I /dev/sda | grep TRIM"
  register: hdparm
  ignore_errors: True

- name: Enable and start weekly filesystem TRIM timer
  service: name=fstrim.timer enabled=yes state=started
  when: "hdparm.rc == 0"
