---
- name: Install terminal packages
  pacman: name="{{ item.value }}" state=present
  with_dict: "{{ terminals }}"
  tag:
    - terminals

- name: Install Aur packages
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  become: True
  with_items:
    - urxvt-resize-font-git
  tags:
    - aur
